Repository chains-project/dirty-waters, pull requests merged in 2025-02, with the labels that each got.

#64 feat: add gradual reporting by default
  README.md
  tool/compare_commits.py
  tool/compare_packages.py
  tool/main.py
  tool/report_diff.py
  tool/report_static.py
Labels: enhancement

#65 fix: request explicit pnpm scope if flag is active
  README.md
  tool/extract_deps.py
  tool/main.py
  tool/tool_config.py
Labels: enhancement, JavaScript

#68 fix: packaging issues, modules not found on pip installation
  README.md
  pyproject.toml
  tool/compare_commits.py
  tool/extract_deps.py
  tool/get_pr_info.py
  tool/get_pr_review.py
  tool/get_user_commit_info.py
  tool/github_repo.py
  tool/main.py
  tool/static_analysis.py
Labels: bug, documentation

#70 fix: generalize maven coordinate extraction for scenarios with more than 4 fields
  tool/extract_deps.py
Labels: bug, Java

#77 chore: simplify CLI usage
  README.md
  tool/main.py
Labels: documentation, enhancement

#79 improve README
  README.md
Labels: documentation
